### ISSUE TITLE
don't work firmware download link

### ISSUE THREAD

**Issue by echadow** [bq/prusa-i3-hephestos#30]
don't work firmware download link.

**Comment by sinuso** [comment]
On page bq support it does not appear. On page in Spanish if.
http://www.bq.com/es/support/prusa

**Comment by echadow** [comment]
thx but i need the firmware in .ino. bq only have the .hex

**Comment by mtowara** [comment]
It's now here:
https://github.com/bq/Marlin

**Comment by sinuso** [comment]
@mtowara There is no compiled firmware or the ino

**Comment by mtowara** [comment]
Yeah, it looks like they removed the ino file, but its still the Marlin src and you can compile it with Arduino using the Makefile

**Comment by ivan-galvez** [comment]
The firmware development sources are maintained on GitHub: https://github.com/bq/Marlin

From version 2.0.0, onwards .ino format file has been dropped. If you want to compile the sources by yourself, you will need to use the provided GNU Makefile. Please refer to the Documentation notes, regarding how to compile the code.

If you want the latest stable release for BQ Prusa i3 Hephestos, you will need to download version 1.4.2. This version still keeps support for .ino files. Sources are accessible from the Releases/Tags page on GitHub: https://github.com/bq/Marlin/releases/tag/1.4.2

**Comment by sinuso** [comment]
Gracias @ivan-galvez. El que no sepa ingles ni compilar, le va a tocar sudar xD

**Comment by echadow** [comment]
hablas español?
